// BE 서버에서는 category_id로 전달
export enum CATEGORY {
  ALL = 0,
  TOP = 1,
  OUTER = 2,
  PANTS = 3,
  DRESS = 4,
  SHOES = 5,
  PROPS = 6,
}

// UI 매핑
export const CATEGORY_LABELS: Record<CATEGORY, string> = {
  [CATEGORY.ALL]: "전체",
  [CATEGORY.TOP]: "상의",
  [CATEGORY.OUTER]: "아우터",
  [CATEGORY.PANTS]: "하의",
  [CATEGORY.DRESS]: "원피스/스커트",
  [CATEGORY.SHOES]: "신발",
  [CATEGORY.PROPS]: "소품/악세사리",
};

export const child_category = [
  { id: 101, categoryName: "맨투맨", category_id: 1 },
  { id: 102, categoryName: "후드", category_id: 1 },
  { id: 103, categoryName: "셔츠/블라우스", category_id: 1 },
  { id: 104, categoryName: "긴소매 티셔츠", category_id: 1 },
  { id: 105, categoryName: "반소매 티셔츠", category_id: 1 },
  { id: 106, categoryName: "니트", category_id: 1 },
  { id: 107, categoryName: "민소매 티셔츠", category_id: 1 },
  { id: 201, categoryName: "후드집업", category_id: 2 },
  { id: 202, categoryName: "가죽/레더", category_id: 2 },
  { id: 203, categoryName: "가디건", category_id: 2 },
  { id: 204, categoryName: "코트", category_id: 2 },
  { id: 206, categoryName: "점퍼", category_id: 2 },
  { id: 301, categoryName: "데님", category_id: 3 },
  { id: 302, categoryName: "트레이닝", category_id: 3 },
  { id: 303, categoryName: "코튼", category_id: 3 },
  { id: 304, categoryName: "슬랙스", category_id: 3 },
  { id: 305, categoryName: "숏팬츠", category_id: 3 },
  { id: 306, categoryName: "레깅스", category_id: 3 },
  { id: 401, categoryName: "미니원피스", category_id: 4 },
  { id: 402, categoryName: "미디원피스", category_id: 4 },
  { id: 403, categoryName: "맥시원피스", category_id: 4 },
  { id: 404, categoryName: "미니스커트", category_id: 4 },
  { id: 405, categoryName: "미디스커트", category_id: 4 },
  { id: 406, categoryName: "롱스커트", category_id: 4 },
  { id: 501, categoryName: "스니커즈", category_id: 5 },
  { id: 502, categoryName: "부츠", category_id: 5 },
  { id: 503, categoryName: "구두", category_id: 5 },
  { id: 504, categoryName: "슬리퍼", category_id: 5 },
  { id: 505, categoryName: "운동화", category_id: 5 },
  { id: 506, categoryName: "기타신발", category_id: 5 },
  { id: 601, categoryName: "가방", category_id: 6 },
  { id: 602, categoryName: "모자", category_id: 6 },
  { id: 603, categoryName: "머플러", category_id: 6 },
  { id: 604, categoryName: "주얼리", category_id: 6 },
  { id: 605, categoryName: "양말", category_id: 6 },
  { id: 606, categoryName: "안경", category_id: 6 },
];
